version: '2.2'
services: 
    mysql :
        image: mysql
        restart: always
        volumes: 
            - ./obo.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: obo
    
    web :
        image: saocd/techmaster-obo-web:1.2.1
        depends_on: 
            - mysql
        ports: 
            - "8080:8080"
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: obo
            DB_USER: root
            DB_PASSWORD: 123
        restart: always